const homeData = [
  {
    id: 1,
    name: "Air",
    rating: 4.7,
    time: "1hr : 52mins",
    desc: "Air ndjek historinë e shitësit të këpucëve Sonny Vaccaro dhe mënyrën se si ai udhëhoqi Nike në ndjekjen e atletit më të madh në historinë e basketbollit: Michael Jordan.",
    starring: "Matt Damon, Ben Affleck, Jason Bateman, Viola Davis",
    genres: "Dramë",
    tags: "Dramë",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "05-Prill-2023",
    list: false,
  },
  {
    id: 2,
    name: "Evil Dead Rise",
    rating: 4.6,
    time: "1hr : 37mins",
    desc: "Një histori e dy motrave të larguara, ribashkimi i të cilave ndërpritet nga rritja e demonëve duke i shtyrë ato në një betejë primare për mbijetesë, ndërsa përballen me versionin më të tmerrshëm të familjes që mund të imagjinohet.",
    starring:
      "Alyssa Sutherland, Lily Sullivan, Morgan Davies, Gabrielle Echols",
    genres: "Horror",
    tags: "Horror",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "21-Prill-2023",
    list: false,
  },
  {
    id: 3,
    name: "John Wick: Chapter 4",
    rating: 4.8,
    time: "2hr : 39mins",
    desc: "John Wick zbulon një rrugë për të mposhtur The High Table. Por përpara se të fitojë lirinë e tij, Wick duhet të përballet me një armik të ri me aleanca të fuqishme anembanë globit dhe forca që i kthejnë miqtë e vjetër në armiq. ",
    starring: "Keanu Reeves, Laurence Fishburne",
    genres: "Aksion, Thriller",
    tags: "Aksion, Thriller",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "13-Mars-2023",
    list: false,
  },
  {
    id: 4,
    name: "Renfield",
    rating: 4.5,
    time: "1hr : 33mins",
    desc: "Njeri i Drakulës dhe i burgosuri në azilin e të çmendurve.",
    starring: "	Nicolas Cage, Nicholas Hoult, Awkwafina, Ben Schwartz",
    genres: "Komedi, Fantazi, Horror",
    tags: "Komedi, Fantazi, Horror",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "14-Prill-2023",
    list: false,
  },
];

export default homeData;
